# Generated by Django 4.2.6 on 2023-10-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddetails',
            name='ytviews',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
