# Generated by Django 4.2.6 on 2023-10-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_adddetails_ytviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddetails',
            old_name='ytviews',
            new_name='if_selected',
        ),
    ]
