# Generated by Django 4.2.6 on 2023-10-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_rename_ytviews_adddetails_if_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddetails',
            old_name='yviews',
            new_name='What_Users_Say',
        ),
        migrations.AlterField(
            model_name='adddetails',
            name='if_selected',
            field=models.BooleanField(default=False),
        ),
    ]
