# Generated by Django 4.2.6 on 2023-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_rename_adddetails_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='if_selected',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
