# Generated by Django 4.2.6 on 2023-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_details_if_selected_alter_details_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='if_selected',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
