# Generated by Django 4.2.6 on 2023-10-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_rename_what_users_say_details_user_feedback_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='User_feedback',
            new_name='user_feedback',
        ),
    ]
